### ISSUE TITLE
Submit change/error/duplicate 

### ISSUE THREAD

**Issue by heskew** [misterkeebs/mkbot#8]
Looks like I accidentally submitted a duplicate and there's nothing I can do about it. :) Would be nice to at least have some feedback loop.

E.g. https://a.mrkeebs.com/catalogs/30-Wildstory-Caps/Lola

**Comment by fcoury** [comment]
I noticed it as well. I will be working on a way to try and identify it :)

**Comment by fcoury** [comment]
![Duplicates](https://p192.p3.n0.cdn.getcloudapp.com/items/9ZuWwvpL/Screen+Recording+2019-11-26+at+12.09+PM.gif)
